# Generated by Django 6.0.4 on 2026-04-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(blank=True, help_text='Optional icon name/class', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Sujan Flats', max_length=255)),
                ('property_type', models.CharField(choices=[('PG', 'Paying Guest'), ('FLAT', 'Flat/Apartment'), ('HOSTEL', 'Private Hostel')], max_length=20)),
                ('configuration', models.CharField(blank=True, help_text='e.g. 1BHK, 2BHK, Shared Room', max_length=100, null=True)),
                ('gender_policy', models.CharField(choices=[('BOYS', 'Boys Only'), ('GIRLS', 'Girls Only'), ('COED', 'Co-ed')], default='COED', max_length=10)),
                ('address', models.TextField()),
                ('walking_distance_bvm', models.CharField(blank=True, help_text='e.g. 5 mins walk to BVM', max_length=100, null=True)),
                ('estimated_rent', models.CharField(help_text='e.g. ₹5000/month', max_length=100)),
                ('broker_fees', models.CharField(blank=True, help_text='e.g. 1 month rent', max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, to='properties.amenity')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('LANDLORD', 'Landlord/Owner'), ('WARDEN', 'Warden'), ('BROKER', 'Broker')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('caption', models.CharField(blank=True, help_text='e.g. Building Exterior, Bedroom', max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Check to make this the main thumbnail')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
