# Generated by Django 6.0.4 on 2026-04-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='numeric_rent',
            field=models.IntegerField(blank=True, help_text='Raw number for search filtering (e.g. 12000)', null=True),
        ),
    ]
