# Generated by Django 6.0.4 on 2026-04-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_numeric_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_coordinates',
            field=models.CharField(blank=True, help_text='e.g., 22.5534, 72.9234 for exact pin drop', max_length=255, null=True),
        ),
    ]
